name: build

on: [push]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        buildType: ["Debug", "Release"]

    steps:
    - name: run-cmake
      uses: lukka/run-cmake@v2.5
      with:
        cmakeBuildType: "${{ matrix.buildType }}"
