name: build

on: [push]

env:
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
  VCPKG_FEATURE_FLAGS: manifests,binarycaching,registries
  VCPKG_GIT_REF: c47216ac7904b09187c119c7e4d010dcf993e3d5

defaults:
  run:
    shell: bash

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        buildType: ["Debug", "Release"]
        buildArch: ["Win32", "x64"]
    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet Credentials
      run: >
        nuget sources add
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        -storepasswordincleartext
        -name "GitHub"
        -username "${{ github.repository_owner }}"
        -password "${{ secrets.GITHUB_TOKEN }}"
    - uses: seanmiddleditch/gha-setup-ninja@v3
    - uses: lukka/run-vcpkg@v7.1
      with:
        setupOnly: true
        vcpkgGitCommitId: ${{ env.VCPKG_GIT_REF }}

    - name: Configure build tools
      uses: ilammy/msvc-dev-cmd@v1.5.0
      with:
        arch: ${{ matrix.buildArch }}

    - name: run-cmake
      env:
        CXXFLAGS: '/WX'
      run: |
        mkdir cmake_out
        cd cmake_out
        cmake -A${{ matrix.buildArch }} ../

        cmake -G Ninja \
          -A${{ matrix.buildArch }} \
          -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" \
          ../

        cmake --build . --config ${{ matrix.buildType }}
    # - name: run-cmake
    #   uses: lukka/run-cmake@v2.5
    #   with:
    #     cmakeAppendedArgs: '-G "Visual Studio 16 2019" -A${{ matrix.buildArch }} -D CMAKE_CXX_FLAGS=/WX'
    #     cmakeBuildType: ${{ matrix.buildType }}



  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        buildType: ["Debug", "Release"]
        buildCompiler:
          - exe: g++-9
            deps: ""
          - exe: clang++-9
            deps: clang-9 libc++-9-dev libc++abi-9-dev
          - exe: clang++-10
            deps: "clang-10 libc++-10-dev libc++abi-10-dev"

    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet Credentials
      run: >
        nuget sources add
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        -storepasswordincleartext
        -name "GitHub"
        -username "${{ github.repository_owner }}"
        -password "${{ secrets.GITHUB_TOKEN }}"
    - uses: seanmiddleditch/gha-setup-ninja@v3
    - uses: lukka/run-vcpkg@v7.1
      with:
        setupOnly: true
        vcpkgGitCommitId: ${{ env.VCPKG_GIT_REF }}

    - name: Add repos
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 15CF4D18AF4F7421
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal main" | sudo tee /etc/apt/sources.list.d/llvm.list
        sudo apt update

    - run: sudo apt install ${{ matrix.buildCompiler.deps }}

    - name: run-cmake
      env:
        CXX: ${{ matrix.buildCompiler.exe }}
        CMAKE_CXX_COMPILER: ${{ matrix.buildCompiler.exe }}
        CXXFLAGS: -Werror -Wall -Wpedantic -Wextra
      run: |
        mkdir cmake_out
        cd cmake_out

        cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.buildType }} \
          -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" \
          ../

        cmake --build .



  build-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        buildType: ["Debug", "Release"]

    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet Credentials
      run: >
        nuget sources add
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        -storepasswordincleartext
        -name "GitHub"
        -username "${{ github.repository_owner }}"
        -password "${{ secrets.GITHUB_TOKEN }}"
    - uses: seanmiddleditch/gha-setup-ninja@v3
    - uses: lukka/run-vcpkg@v7.1
      with:
        setupOnly: true
        vcpkgGitCommitId: ${{ env.VCPKG_GIT_REF }}

    - name: run-cmake
      env:
        CXXFLAGS: -Werror -Wall -Wpedantic -Wextra
      run: |
        mkdir cmake_out
        cd cmake_out

        cmake -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ matrix.buildType }} \
          -DCMAKE_TOOLCHAIN_FILE="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" \
          ../

        cmake --build .
